# Generated by Django 6.0.1 on 2026-09-05 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0004_dealer_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('stripe_created_at', models.DateTimeField()),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-stripe_created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DealerSubscriptionTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('demo', 'Try the demo'), ('licensing', 'Online licensing'), ('contracts', 'Online contracts'), ('complete', 'Complete online sale')], max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('terms_version', models.CharField(max_length=30)),
                ('terms_sha256', models.CharField(max_length=64)),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_acceptances', to='dealers.dealer')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('dealer', 'plan', 'monthly_price', 'currency', 'terms_sha256'), name='unique_dealer_subscription_offer_acceptance')],
            },
        ),
    ]
