# Generated by Django 6.0.1 on 2026-09-05 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_remove_dealer_subscription_terms_accepted_at_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dealersubscriptiontermsacceptance',
            name='unique_dealer_subscription_offer_acceptance',
        ),
        migrations.AddConstraint(
            model_name='dealersubscriptiontermsacceptance',
            constraint=models.UniqueConstraint(fields=('dealer', 'plan', 'monthly_price', 'currency', 'terms_version', 'terms_sha256'), name='unique_dealer_subscription_offer_acceptance'),
        ),
    ]
