# Generated by Django 6.0.1 on 2026-09-07 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_dealersubscriptiontermsacceptance_plan'),
        ('seo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSubscriptionTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly report'), ('quarterly', 'Quarterly report'), ('biannual', 'Bi-annual report'), ('oneoff', 'One-off report')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('terms_version', models.CharField(max_length=30)),
                ('terms_sha256', models.CharField(max_length=64)),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_acceptances', to='seo.seosubscriber')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'plan', 'price', 'currency', 'terms_version', 'terms_sha256'), name='unique_seo_subscription_offer_acceptance')],
            },
        ),
    ]
