# Generated by Django 6.0.1 on 2026-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("business", models.CharField(max_length=180)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("website", models.URLField(blank=True)),
                (
                    "help_with",
                    models.CharField(
                        choices=[
                            ("website", "Dealer website"),
                            ("inventory", "Inventory, parts, service or hire"),
                            ("automation", "Business automation"),
                            ("unsure", "Not sure yet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
