# Generated by Django 6.0.1 on 2026-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="help_with",
            field=models.CharField(
                choices=[
                    ("website", "Dealer website"),
                    ("inventory", "Inventory, parts, service or hire"),
                    ("automation", "Business automation"),
                    ("everything", "All of the above"),
                    ("unsure", "Not sure yet"),
                ],
                max_length=20,
            ),
        ),
    ]
