# Generated by Django 6.0.1 on 2026-08-31 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_enquiry_status_notification"),
        ("dealers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="dealers.dealer",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("dealer", "Dealer"),
                    ("manual", "Manual email"),
                ],
                max_length=20,
            ),
        ),
    ]
