# Generated by Django 6.0.1 on 2026-09-05 03:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enquiry_configuration_and_builder_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensing_price', models.DecimalField(decimal_places=2, default=Decimal('149.00'), max_digits=8)),
                ('contracts_price', models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=8)),
                ('complete_price', models.DecimalField(decimal_places=2, default=Decimal('199.00'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licensing settings',
                'verbose_name_plural': 'Licensing settings',
            },
        ),
    ]
