# Generated by Django 6.0.1 on 2026-09-05 06:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_licensingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensingsettings',
            name='complete_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('199.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='licensingsettings',
            name='contracts_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='licensingsettings',
            name='licensing_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('149.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
