# Generated by Django 6.0.1 on 2026-09-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_enquiry_business'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_seo_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='seo.seosubscriber'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('seo', 'SEO customer'), ('manual', 'Manual email')], max_length=20),
        ),
    ]
