# Generated by Django 6.0.1 on 2026-09-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_sitesettings_ai_readiness_audit_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
