# Generated by Django 6.0.8 on 2026-10-02 03:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='gbp_audit_price',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_biannual_price',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_monthly_price',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_quarterly_price',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_subscription_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('225.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
