# Generated by Django 6.0.8 on 2026-10-02 07:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def set_launch_prices(apps, schema_editor):
    # The new defaults only reach a fresh row; the existing settings row would
    # keep the placeholder prices, so the launch prices are written to it too.
    apps.get_model('core', 'SiteSettings').objects.filter(pk=1).update(
        seo_oneoff_price=Decimal('550.00'),
        seo_subscription_price=Decimal('499.00'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seo_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_oneoff_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('550.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_subscription_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('499.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.RunPython(set_launch_prices, migrations.RunPython.noop),
    ]
