# Generated by Django 6.0.8 on 2026-10-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seo_plan_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='freethedesk', max_length=180)),
                ('legal_name', models.CharField(blank=True, help_text='The legal entity, if it differs from the business name. Printed in the header and footer.', max_length=180)),
                ('abn', models.CharField(blank=True, default='11 493 753 896', max_length=32, verbose_name='ABN')),
                ('address', models.TextField(blank=True, default='Perth, Western Australia', help_text='One line per printed line.')),
                ('email', models.EmailField(blank=True, default='hello@freethedesk.com.au', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.CharField(blank=True, default='freethedesk.com.au', max_length=200)),
                ('bank_account_name', models.CharField(blank=True, max_length=180)),
                ('bank_bsb', models.CharField(blank=True, max_length=7, verbose_name='BSB')),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('payment_note', models.CharField(blank=True, help_text='Printed under the bank details, e.g. another way to pay.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice settings',
                'verbose_name_plural': 'Invoice settings',
            },
        ),
    ]
