# Generated by Django 6.0.8 on 2026-10-07 11:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """Prices for the quoted services, editable in the admin.

    An hourly rate and the discovery hours paid upfront; three website
    packages, each a page count at a per-page price; and a "from" price for web
    applications and for automation. The defaults are a starting proposal for
    staff to confirm, not settled prices.
    """


    dependencies = [
        ('core', '0017_invoice_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='automation_from_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1200.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discovery_hours',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='web_app_from_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('9000.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_connect_page_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('700.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_connect_pages',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_grow_page_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('600.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_grow_pages',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_launch_page_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_launch_pages',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
