# Generated by Django 6.0.8 on 2026-10-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    """Only the enquiry types a live form can create.

    The dealership builder and the free-form enquiry endpoint it posted to are
    gone, and with them the only routes to website_builder, inventory and
    unsure. Production held no enquiries when this ran, so no row is left with
    a retired value. The kept labels now say what the project form asks.
    """

    dependencies = [
        ('core', '0018_service_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='help_with',
            field=models.CharField(choices=[('website', 'Website'), ('automation', 'Business automation'), ('ai_readiness', 'AI readiness check'), ('everything', 'Website and automation')], max_length=20),
        ),
    ]
