# Generated by Django 6.0.8 on 2026-10-07 15:29

from django.db import migrations, models


BANK = {
    "bank_account_name": "Ethan Daniel Betts-Ingram",
    "bank_bsb": "067872",
    "bank_account_number": "74596050",
}


def fill_blank_bank_details(apps, schema_editor):
    """An existing settings row takes the defaults only where a field is still blank."""
    InvoiceSettings = apps.get_model("core", "InvoiceSettings")
    for settings in InvoiceSettings.objects.all():
        changed = [field for field, value in BANK.items() if not getattr(settings, field)]
        for field in changed:
            setattr(settings, field, BANK[field])
        if changed:
            settings.save(update_fields=changed)


class Migration(migrations.Migration):
    """The business bank account as the invoice settings' default."""


    dependencies = [
        ('core', '0020_website_packages_and_web_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='bank_account_name',
            field=models.CharField(blank=True, default='Ethan Daniel Betts-Ingram', max_length=180),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='bank_account_number',
            field=models.CharField(blank=True, default='74596050', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='bank_bsb',
            field=models.CharField(blank=True, default='067872', max_length=7, verbose_name='BSB'),
        ),
        migrations.RunPython(fill_blank_bank_details, migrations.RunPython.noop),
    ]
