# Generated by Django 6.0.8 on 2026-10-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_invoice_bank_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='web_app_from_price',
        ),
    ]
