# Generated by Django 6.0.8 on 2026-10-08 04:51

import core.models.package_order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_web_app_from_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_reference', models.CharField(default=core.models.package_order.new_checkout_reference, editable=False, max_length=64, unique=True)),
                ('package', models.CharField(choices=[('website_small', 'Website package 1'), ('website_large', 'Website package 2'), ('web_application', 'Web application discovery'), ('automation_discovery', 'Automation discovery')], max_length=40)),
                ('package_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_now', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('payment_pending', 'Payment pending'), ('paid', 'Paid')], default='payment_pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='help_with',
            field=models.CharField(choices=[('website', 'Website'), ('automation', 'Business automation'), ('ai_readiness', 'AI readiness check'), ('everything', 'Website and automation')], max_length=20),
        ),
    ]
