# Generated by Django 6.1 on 2026-09-19 09:15

import django.db.models.deletion
import django.db.models.manager
import identity.models.storage
import identity.models.verification
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `makemigrations` writes the *latest* dealers migration here, but all this
    # app needs is for `Dealer` to exist, which it does from 0001. Pinning to
    # the latest couples this leaf to dealers/0010, which depends on the
    # payments backfill — so reaching this app's leaf drags payments forward and
    # breaks the agreement-migration test's ability to rewind it. Relaxed
    # deliberately, the same way sales/0001 and documents/0001 are; do not let a
    # regenerate put the latest back.
    dependencies = [
        ('dealers', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('manual', 'Reviewed by the dealer'), ('stripe', 'Stripe Identity')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the customer'), ('submitted', 'Waiting for review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('front_image', models.FileField(blank=True, storage=identity.models.storage.private_identity_storage, upload_to=identity.models.verification.identity_image_path)),
                ('front_status', models.CharField(choices=[('missing', 'Not uploaded'), ('submitted', 'Waiting for review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='missing', max_length=20)),
                ('front_reason', models.TextField(blank=True)),
                ('back_image', models.FileField(blank=True, storage=identity.models.storage.private_identity_storage, upload_to=identity.models.verification.identity_image_path)),
                ('back_status', models.CharField(choices=[('missing', 'Not uploaded'), ('submitted', 'Waiting for review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='missing', max_length=20)),
                ('back_reason', models.TextField(blank=True)),
                ('selfie_image', models.FileField(blank=True, storage=identity.models.storage.private_identity_storage, upload_to=identity.models.verification.identity_image_path)),
                ('selfie_status', models.CharField(choices=[('missing', 'Not uploaded'), ('submitted', 'Waiting for review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='missing', max_length=20)),
                ('selfie_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='dealers.dealer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='sales.sale')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
