# Generated by Django 6.0.1 on 2026-09-05 02:26

import dealers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealer',
            name='payment_status',
            field=models.CharField(choices=[('demo', 'Demo'), ('payment_pending', 'Payment pending'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], db_index=True, default='demo', max_length=20),
        ),
        migrations.AddField(
            model_name='dealer',
            name='plan',
            field=models.CharField(choices=[('demo', 'Try the demo'), ('licensing', 'Online licensing'), ('contracts', 'Online contracts'), ('complete', 'Complete online sale')], db_index=True, default='demo', max_length=20),
        ),
        migrations.AddField(
            model_name='dealer',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('changes_requested', 'Changes requested'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='not_started', max_length=24)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('dealer_licence_number', models.CharField(blank=True, max_length=50)),
                ('repairer_licence_number', models.CharField(blank=True, max_length=50)),
                ('organisation_code', models.CharField(blank=True, max_length=50)),
                ('abn', models.CharField(blank=True, max_length=20)),
                ('acn', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, default='WA', max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('authorised_officer_name', models.CharField(blank=True, max_length=200)),
                ('authorised_officer_licence_number', models.CharField(blank=True, max_length=50)),
                ('authorised_officer_date_of_birth', models.DateField(blank=True, null=True)),
                ('declared_at', models.CharField(blank=True, max_length=100)),
                ('dealer_licence_document', models.FileField(blank=True, upload_to=dealers.models.dealer_document_path)),
                ('authorised_officer_identity_document', models.FileField(blank=True, upload_to=dealers.models.dealer_document_path)),
                ('business_evidence_document', models.FileField(blank=True, upload_to=dealers.models.dealer_document_path)),
                ('condition_choices', models.JSONField(blank=True, default=dict)),
                ('conditions_version', models.PositiveIntegerField(default=1)),
                ('conditions_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('conditions_accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_dealer_conditions', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='dealers.dealer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dealer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
