# Generated by Django 6.0.1 on 2026-09-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealer_cancel_at_period_end_dealer_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='subscription_terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='subscription_terms_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='subscription_terms_version',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
