# Generated by Django 6.0.1 on 2026-09-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealer_subscription_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='state',
            field=models.CharField(choices=[('WA', 'Western Australia'), ('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], default='WA', max_length=3),
        ),
    ]
