# Generated by Django 6.0.1 on 2026-09-05 06:13

import dealers.models
import dealers.storage
from django.db import migrations, models


def preserve_canonical_details_and_acceptances(apps, schema_editor):
    Dealer = apps.get_model('dealers', 'Dealer')
    DealerProfile = apps.get_model('dealers', 'DealerProfile')
    Acceptance = apps.get_model('payments', 'DealerSubscriptionTermsAcceptance')
    prices = {'licensing': '149.00', 'contracts': '99.00', 'complete': '199.00'}
    valid_states = {'WA', 'NSW', 'VIC', 'QLD', 'SA', 'TAS', 'ACT', 'NT'}

    for profile in DealerProfile.objects.select_related('dealer', 'dealer__user'):
        dealer = profile.dealer
        dealer.business_name = profile.trading_name or dealer.business_name
        dealer.phone = profile.phone or dealer.phone
        dealer.email = profile.email or dealer.email
        if profile.state in valid_states:
            dealer.state = profile.state
        dealer.save(update_fields=['business_name', 'phone', 'email', 'state'])

    for dealer in Dealer.objects.select_related('user').exclude(subscription_terms_accepted_at=None):
        if dealer.plan not in prices:
            continue
        acceptance = Acceptance.objects.create(
            dealer=dealer,
            accepted_by=dealer.user,
            plan=dealer.plan,
            monthly_price=prices[dealer.plan],
            currency='AUD',
            terms_version=dealer.subscription_terms_version or 'legacy',
            terms_sha256='legacy-not-recorded',
            accepted_ip=dealer.subscription_terms_accepted_ip,
            stripe_checkout_session_id=dealer.stripe_checkout_session_id or '',
        )
        Acceptance.objects.filter(pk=acceptance.pk).update(
            accepted_at=dealer.subscription_terms_accepted_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_dealer_state'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(preserve_canonical_details_and_acceptances, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dealer',
            name='subscription_terms_accepted_at',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='subscription_terms_accepted_ip',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='subscription_terms_version',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='trading_name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='stripe_last_event_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='authorised_officer_identity_document',
            field=models.FileField(blank=True, storage=dealers.storage.private_document_storage, upload_to=dealers.models.dealer_document_path),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='business_evidence_document',
            field=models.FileField(blank=True, storage=dealers.storage.private_document_storage, upload_to=dealers.models.dealer_document_path),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='dealer_licence_document',
            field=models.FileField(blank=True, storage=dealers.storage.private_document_storage, upload_to=dealers.models.dealer_document_path),
        ),
    ]
