# Generated by Django 6.0.1 on 2026-09-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_remove_dealer_subscription_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='email',
        ),
    ]
