# Generated by Django 6.1 on 2026-09-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0008_dealerprofile_onboarding_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='stripe_last_event_created_at',
        ),
    ]
