# Generated by Django 6.1 on 2026-09-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Explicit, and load-bearing. The payments backfill reads
        # stripe_checkout_session_id to give an in-flight checkout something to
        # land on; without this dependency Django is free to plan that removal
        # before the backfill, and the historical model state the backfill sees
        # would no longer have the column.
        ('dealers', '0009_remove_dealer_stripe_last_event_created_at'),
        ('payments', '0008_backfill_shared_payment_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='stripe_checkout_session_id',
        ),
    ]
