# Generated by Django 6.1 on 2026-09-19 08:18

import dealers.models
import dealers.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0010_remove_dealer_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerprofile',
            name='conditions_accepted_at',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='conditions_accepted_by',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='conditions_accepted_ip',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='conditions_version',
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='bank_bsb',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='signature_image',
            field=models.FileField(blank=True, storage=dealers.utils.storage.private_document_storage, upload_to=dealers.models.dealer_document_path),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='signature_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='trading_hours_note',
            field=models.TextField(blank=True),
        ),
    ]
