# Generated by Django 6.1 on 2026-09-19 08:34

import django.db.models.deletion
import django.db.models.manager
import documents.models.form_template
import documents.models.sale_document
import documents.models.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `makemigrations` writes the *latest* dealers migration here, but all this
    # app needs is for `Dealer` to exist, which it does from 0001. Pinning to
    # the latest couples this leaf to dealers/0010, which depends on the
    # payments backfill — so reaching this app's leaf drags payments forward and
    # breaks the agreement-migration test's ability to rewind it. Relaxed
    # deliberately, the same way sales/0001 is; do not let a regenerate put the
    # latest back.
    dependencies = [
        ('dealers', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vl17', 'VL17 — Application to licence a vehicle'), ('mr9b', 'MR9B — Notification of change of owner'), ('form_5a_motorcycle', 'Form 5A — Statutory warranty (motorcycle)'), ('form_6', 'Form 6 — No statutory warranty')], db_index=True, max_length=32)),
                ('version_label', models.CharField(max_length=32)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('file', models.FileField(storage=documents.models.storage.private_template_storage, upload_to=documents.models.form_template.form_template_path)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', '-effective_from', '-id'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version_label'), name='form_template_kind_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale_contract', 'Vehicle Sale Contract'), ('licensing_form', 'Licensing form'), ('authority_to_lodge', 'Authority to Lodge')], max_length=32)),
                ('file', models.FileField(storage=documents.models.storage.private_document_storage, upload_to=documents.models.sale_document.sale_document_path)),
                ('template_version', models.CharField(blank=True, max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('signer_name', models.CharField(blank=True, max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signing_statement', models.TextField(blank=True)),
                ('document_sha256', models.CharField(blank=True, max_length=64)),
                ('signing_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signing_user_agent', models.CharField(blank=True, max_length=500)),
                ('signed_by_role', models.CharField(blank=True, choices=[('customer', 'Customer'), ('dealer', 'Dealer')], max_length=20)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='dealers.dealer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.sale')),
            ],
            options={
                'ordering': ['kind'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('sale', 'kind'), name='sale_document_kind_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
