# Generated by Django 6.0.1 on 2026-09-07 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('plan', models.CharField(choices=[('monthly', 'Monthly report'), ('quarterly', 'Quarterly report'), ('biannual', 'Bi-annual report'), ('oneoff', 'One-off report')], db_index=True, default='quarterly', max_length=20)),
                ('payment_status', models.CharField(choices=[('payment_pending', 'Payment pending'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], db_index=True, default='payment_pending', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_last_event_created_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('active', 'Active')], db_index=True, default='not_started', max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('search_console_property', models.CharField(blank=True, max_length=255)),
                ('primary_location', models.CharField(blank=True, max_length=180)),
                ('target_keywords', models.TextField(blank=True)),
                ('competitors', models.TextField(blank=True)),
                ('google_business_profile_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='seo.seosubscriber')),
            ],
        ),
    ]
