# Generated by Django 6.0.1 on 2026-09-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted')], db_index=True, default='not_started', max_length=20),
        ),
    ]
