# Generated by Django 6.1 on 2026-09-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_separate_report_type_and_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seosubscriber',
            name='stripe_last_event_created_at',
        ),
    ]
