# Generated by Django 6.0.8 on 2026-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_remove_seosubscriber_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seosubscriber',
            name='report_type',
        ),
        migrations.AlterField(
            model_name='seosubscriber',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bimonthly', 'Every two months'), ('quarterly', 'Quarterly'), ('biannual', 'Every six months'), ('oneoff', 'One-off')], db_index=True, default='monthly', max_length=20),
        ),
    ]
