# Generated by Django 6.0.8 on 2026-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_drop_report_type_add_bimonthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosubscriber',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('bimonthly', 'Every two months'), ('quarterly', 'Quarterly'), ('biannual', 'Every six months'), ('oneoff', 'SEO audit')], db_index=True, default='monthly', max_length=20),
        ),
    ]
