# Generated by Django 6.0.8 on 2026-10-02 11:01

import django.db.models.deletion
from django.db import migrations, models


def activate_paid_pending(apps, schema_editor):
    """Payment now switches an account on; there is no approval step after it.

    Accounts that paid before that change are still waiting on an approval that
    will never come, and no new payment event will arrive to activate them.
    """
    SeoSubscriber = apps.get_model("seo", "SeoSubscriber")
    SeoSubscriber.objects.filter(status="pending", payment_status__in=["active", "paid"]).update(
        status="active"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_audit_plan_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoprofile',
            name='onboarding_status',
        ),
        migrations.RemoveField(
            model_name='seoprofile',
            name='submitted_at',
        ),
        migrations.CreateModel(
            name='SeoSetupStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('search_console', 'Google Search Console'), ('google_analytics', 'Google Analytics'), ('business_profile', 'Google Business Profile'), ('google_ads', 'Google Ads'), ('clarity', 'Microsoft Clarity'), ('enquiries', 'Your enquiries')], max_length=32)),
                ('state', models.CharField(choices=[('not_started', 'Not started'), ('marked_done', 'Marked done'), ('confirmed', 'Confirmed')], default='not_started', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('marked_done_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_steps', to='seo.seosubscriber')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'key'), name='seo_setup_step_unique_key')],
            },
        ),
        migrations.RunPython(activate_paid_pending, migrations.RunPython.noop),
    ]
