# Generated by Django 6.0.8 on 2026-10-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0011_four_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosubscriber',
            name='password_claim_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
