# Generated by Django 6.0.8 on 2026-10-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0012_subscriber_password_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seosubscriber',
            name='password_claim_hash',
        ),
    ]
