# Generated by Django 6.1 on 2026-09-19 05:38

import django.db.models.deletion
import django.db.models.manager
import sales.models.sale
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `makemigrations` writes the *latest* dealers migration here, but all this
    # app needs is for `Dealer` to exist, which it does from 0001. Pinning to
    # the latest coupled the sales leaf to dealers/0010, which depends on the
    # payments backfill — so reaching this app's leaf dragged payments forward
    # and broke the agreement-migration test's ability to rewind it. Relaxed
    # deliberately; do not let a regenerate put 0010 back.
    dependencies = [
        ('dealers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('access_token', models.CharField(default=sales.models.sale.generate_access_token, editable=False, max_length=64, unique=True)),
                ('access_password_hash', models.CharField(blank=True, max_length=128)),
                ('access_failure_count', models.PositiveIntegerField(default=0)),
                ('access_locked_until', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('portal', 'Keyed in the dealer portal')], default='portal', max_length=20)),
                ('produces', models.CharField(choices=[('licensing', 'Licensing only'), ('contracts', 'Contracts only'), ('complete', 'Licensing and contracts')], max_length=20)),
                ('vehicle_class', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('moped', 'Moped')], default='motorcycle', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('demo', 'Demo')], max_length=10)),
                ('make', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=60)),
                ('colour', models.CharField(blank=True, max_length=60)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('engine_number', models.CharField(blank=True, max_length=64)),
                ('engine_capacity_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('is_electric', models.BooleanField(default=False)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('registration', models.CharField(blank=True, max_length=20)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('registration_months_included', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stock_number', models.CharField(blank=True, max_length=64)),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fulfilment_method', models.CharField(choices=[('pickup', 'Collection'), ('delivery', 'Delivery')], default='delivery', max_length=20)),
                ('delivery_address_line1', models.CharField(blank=True, max_length=255)),
                ('delivery_suburb', models.CharField(blank=True, max_length=120)),
                ('delivery_state', models.CharField(blank=True, max_length=3)),
                ('delivery_postcode', models.CharField(blank=True, max_length=16)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('purchaser_is_licence_holder', models.BooleanField(default=True)),
                ('purchaser_family_name', models.CharField(blank=True, max_length=120)),
                ('purchaser_given_names', models.CharField(blank=True, max_length=120)),
                ('purchaser_address_line1', models.CharField(blank=True, max_length=255)),
                ('purchaser_suburb', models.CharField(blank=True, max_length=120)),
                ('purchaser_postcode', models.CharField(blank=True, max_length=16)),
                ('licence_family_name', models.CharField(blank=True, max_length=120)),
                ('licence_given_names', models.CharField(blank=True, max_length=120)),
                ('licence_number', models.CharField(blank=True, max_length=64)),
                ('licence_date_of_birth', models.DateField(blank=True, null=True)),
                ('licensee_address_line1', models.CharField(blank=True, max_length=255)),
                ('licensee_suburb', models.CharField(blank=True, max_length=120)),
                ('licensee_postcode', models.CharField(blank=True, max_length=16)),
                ('kept_primarily_in_wa', models.BooleanField(default=True)),
                ('licensed_to_company', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('company_acn', models.CharField(blank=True, max_length=11)),
                ('company_organisation_code', models.CharField(blank=True, max_length=64)),
                ('warranty_acknowledgement_key', models.CharField(blank=True, max_length=64)),
                ('warranty_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_customer', 'Awaiting customer'), ('awaiting_identity_review', 'Awaiting identity review'), ('ready_to_sign', 'Ready to sign'), ('signed', 'Signed by customer'), ('accepted', 'Accepted by dealer'), ('awaiting_payment', 'Awaiting payment'), ('payment_confirmed', 'Payment confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32)),
                ('link_sent_at', models.DateTimeField(blank=True, null=True)),
                ('details_updated_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_notified_at', models.DateTimeField(blank=True, null=True)),
                ('customer_marked_paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='dealers.dealer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('actor_label', models.CharField(blank=True, max_length=120)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_events', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='dealers.dealer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.sale')),
            ],
            options={
                'ordering': ['at', 'id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0), ('deposit_amount__gte', 0), models.Q(('vehicle_price__isnull', True), ('vehicle_price__gte', 0), _connector='OR'), models.Q(('balance_amount__isnull', True), ('balance_amount__gte', 0), _connector='OR')), name='sale_amounts_non_negative'),
        ),
    ]
