# Generated by Django 6.1 on 2026-09-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_backfill_sale_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='access_failure_count',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='access_locked_until',
        ),
    ]
